package parsers

import (
	"regexp"
	"strings"

	"go.wzykubek.xyz/sieveman/pkg/proto"
)

func ParseResponse(respStr string) proto.Response {
	if respStr == "" {
		return nil
	}

	// This regular expression was generated by Copilot.
	// It SHOULD parse a string containing three parts with the known pattern:
	// 		P1 (P2 ...) "P3 ..."
	//
	// where:
	//		P1		- is mandatory and does not contain whitespace
	//		(P2)	- is optional, contains parentheses, and can contain whitespace inside
	//		"P3"	- is optional, contains quotation marks, and can contain whitespace inside
	//
	// When P2 or "P3" is not present, it MUST return an empty string for those parts.
	re := regexp.MustCompile(`^(\S+)\s*(\([^)]*\))?\s*("[^"]*")?$`)
	matches := re.FindStringSubmatch(respStr)

	resp := matches[1]
	code := ParseResponseCode(matches[2])
	msg := strings.Trim(matches[3], "\"")

	switch resp {
	case "OK":
		return proto.ResponseOK{ResponseCode: code, Msg: msg}
	case "NO":
		return proto.ResponseNO{ResponseCode: code, Msg: msg}
	case "BYE":
		return proto.ResponseBYE{ResponseCode: code, Msg: msg}
	default:
		return nil
	}
}

func ParseResponseCode(codeStr string) proto.ResponseCode {
	if codeStr == "" {
		return nil
	}

	// This regular expression was generated by Copilot.
	// It SHOULD parse a string containing two parts with the known pattern in parentheses:
	// 		(P1 "P2 ...")
	//
	// where:
	//		P1		- is mandatory and does not contain whitespace
	//		"P2"	- is optional, contains quotation marks, and can contain whitespace inside
	//
	// When "P2" is not present, it MUST return an empty string for that part.
	// It also removes the surrounding parentheses.
	re := regexp.MustCompile(`^\((\S+)\s*("[^"]*")?\)$`)
	matches := re.FindStringSubmatch(codeStr)

	code := matches[1]
	msg := strings.Trim(matches[2], "\"")

	switch code {
	case "TAG":
		return proto.Tag{Msg: msg, ChildCode: nil}
	default:
		return nil
	}
}

func ParseMessage(msgStr string) proto.Message {
	if msgStr == "" {
		return proto.Message{}
	}

	// This regular expression was generated by Copilot.
	// It SHOULD parse string containing three parts with known pattern:
	// 		"P1 ..." "P2 ..."
	//
	// where:
	// 		"P1"	- is required
	//		"P2" 	- is optional
	//
	// When there is not "P2" it MUST return empty string.
	re := regexp.MustCompile(`^("[^"]*")(?:\s*("[^"]*"))?$`)
	matches := re.FindStringSubmatch(msgStr)

	return proto.Message{Key: matches[1], Value: matches[2]}
}
