package client

import (
	"regexp"
	"strings"

	"go.wzykubek.xyz/sieveman/pkg/proto"
)

func parseResponse(respStr string) proto.Response {
	if respStr == "" {
		return nil
	}

	// This regular expression was generated by Copilot.
	// It SHOULD parse a string containing three parts with the known pattern:
	// 		P1 (P2 ...) "P3 ..."
	//
	// where:
	//		P1		- is mandatory and does not contain whitespace
	//		(P2)	- is optional, contains parentheses, and can contain whitespace inside
	//		"P3"	- is optional, contains quotation marks, and can contain whitespace inside
	//
	// When P2 or "P3" is not present, it MUST return an empty string for those parts.
	re := regexp.MustCompile(`^(\S+)\s*(\([^)]*\))?\s*("[^"]*")?$`)
	matches := re.FindStringSubmatch(strings.TrimSpace(respStr))
	if len(matches) <= 2 {
		return nil
	}

	resp := matches[1]
	code := parseResponseCode(matches[2])
	msg := strings.Trim(matches[3], "\"")

	switch resp {
	case "OK":
		return proto.Ok{ResponseCode: code, Msg: msg}
	case "NO":
		return proto.No{ResponseCode: code, Msg: msg}
	case "BYE":
		return proto.Bye{ResponseCode: code, Msg: msg}
	default:
		return nil
	}
}

func parseResponseCode(codeStr string) proto.ResponseCode {
	if codeStr == "" {
		return nil
	}

	// This regular expression was generated by Copilot.
	// It SHOULD parse a string containing two parts with the known pattern in parentheses:
	// 		(P1 "P2 ...")
	//
	// where:
	//		P1		- is mandatory and does not contain whitespace
	//		"P2"	- is optional, contains quotation marks, and can contain whitespace inside
	//
	// When "P2" is not present, it MUST return an empty string for that part.
	// It also removes the surrounding parentheses.
	re := regexp.MustCompile(`^\((\S+)\s*("[^"]*")?\)$`)
	matches := re.FindStringSubmatch(codeStr)

	code := strings.Split(matches[1], "/")
	msg := strings.Trim(matches[2], "\"")

	// TODO: Make it simpler, this is overengineered
	switch code[0] {
	case "TAG":
		return proto.Tag{Msg: msg, ChildCode: nil}
	case "NONEXISTENT":
		return proto.NonExistent{Msg: "", ChildCode: nil}
	case "QUOTA":
		switch code[1] {
		case "MAXSIZE":
			return proto.Quota{Msg: "", ChildCode: proto.MaxSize{Msg: msg, ChildCode: nil}}
		default:
			return proto.Quota{Msg: msg, ChildCode: nil}
		}
	default:
		return nil
	}
}

// ReadResponse is a low level method to read and parse response from server.
// It returns parsed response, slice of messages and error if any.
func (c *Client) ReadResponse() (_ proto.Response, messages []string, err error) {
	for {
		var line string
		line, err = c.Reader.ReadString('\n')
		if c.Reader.Buffered() == 0 {
			if resp := parseResponse(line); resp != nil {
				return resp, messages, nil
			}
		}
		if err != nil {
			return nil, messages, err
		}

		if resp := parseResponse(line); resp != nil {
			return resp, messages, nil
		} else {
			messages = append(messages, line)
		}
	}
}
